// <auto-generated />
using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: Guid("23dd67ee-5b4f-4822-99e1-95ae219c175b")]
[assembly: CLSCompliant(true)]
[assembly: InternalsVisibleTo("KnowledgeInterchangeFormat.Tests")]
